import MultipleSelect from "../multiselect/multiselect";

const options = () => {
  return (
    <div>
      <MultipleSelect
        options={[
          "Action",
          "Adventure",
          "Indie",
          "RPG",
          "Simulation",
          "Strategy",
          "Sports",
          "Racing",
        ]}
        title="Genre"
      />
      <MultipleSelect
        options={[
          "Single-player",
          "Multi-player",
          "PvP",
          "Online PvP",
          "LAN PvP",
          "Co-op",
          "Online Co-op",
          "LAN Co-op",
        ]}
        title="Category"
      />
      <MultipleSelect
        options={[
          "Inc",
          "Darkflow Software",
          "Artplant",
          "Telltale Games",
          "Santa Monica Studio",
          "Gone North Games",
          "FromSoftware",
          "Soviet Games",
          "DrinkBox Studios",
          "Bungie",
          "poncle",
          "Hidden Path Entertainment",
          "Running With Scissors",
          "Starbreeze",
          "Ubisoft Bucharest",
          "Raven Software",
          "Vostok Games",
          "Paradox Development Studio",
          "Jesse Makkonen",
          "YAGER",
          "Virtual Basement LLC",
          "BioWare",
          "mestiez",
          "Scott Cawthon",
          "Creative Assembly",
          "Skybox Labs",
          "DICE",
          "Ludeon Studios",
          "Gearbox Software",
          "Rockstar North / Toronto",
          "Volition",
          "Square Enix",
          "Ltd.",
          "Treyarch",
          "Northwood Studios",
          "Playground Games",
          "Aspyr (Linux)",
          "Larian Studios",
          "Triternion",
          "Reloaded Productions",
          "Runic Games",
          "Ubisoft Belgrade",
          "Fredaikis AB",
          "Hopoo Games",
          "IllFonic",
          "Landfall",
          "Oddworld Inhabitants",
          "Ninja Kiwi",
          "Techland",
          "Machine Games",
          "DONTNOD Entertainment",
          "Free Lives",
          "Feral Interactive (Linux)",
          "tobyfox",
          "Chromatic Games",
          "1047 Games",
          "Subset Games",
          "Hello Games",
          "ConcernedApe",
          "Massive Entertainment",
          "Funcom",
          "Ubisoft Annecy",
          "Introversion Software",
          "Stunlock Studios",
          "Ubisoft Toronto",
          "Crazy Rocks Studios",
          "Senscape",
          "High Moon Studios",
          "Psyonix LLC",
          "Freejam",
          "Nik Nak Studios",
          "NetherRealm Studios",
          "Dodge Roll",
          "WOLCEN Studio",
          "Tortuga Team",
          "Spearhead Games",
          "Bungie",
          "Mediatonic",
          "CD PROJEKT RED",
          "Ubisoft Milan",
          "Reflections",
          "Grinding Gear Games",
          "Shanghai",
          "Kinetic Games",
          "Arc System Works",
          "Ltd.",
          "THQ Nordic",
          "Atelier 801",
          "Iron Lore Entertainment",
          "Wicked Witch",
          "BeamNG",
          "SEGA",
          "Eagle Dynamics SA",
          "Toadman Interactive",
          "Re-Logic",
          "Splash Damage",
          "Targem Games",
          "Klei Entertainment",
          "CCP",
          "FishSoft",
          "Wallpaper Engine Team",
          "Ubisoft Paris",
          "Team Salvato",
          "The Fun Pimps",
          "Nadeo",
          "IMCGAMES Co.",
          "MOB Games",
          "BetaDwarf",
          "gamigo US Inc.",
          "Fishing Planet LLC",
          "2K Australia",
          "Ghost Games",
          "Arkane Studios",
          "Demonware",
          "Frontier Developments",
          "2K China",
          "Free Reign Entertainment",
          "Studio Wildcard",
          "Team17",
          "Monolith Productions",
          "Crytek",
          "Rockstar Games",
          "LLC",
          "The Indie Stone",
          "Valve",
          "24 Entertainment",
          "Amazon Games",
          "Masangsoft",
          "Activision Shanghai",
          "Visual Concepts",
          "KW Studios",
          "CAPCOM Co.",
          "Worlds Edge",
          "Ghost Ship Games",
          "Ensemble Studios",
          "Wild Shadow Studios",
          "Kaos Studios",
          "Playwing LTD",
          "Deca Games",
          "Studio MDHR Entertainment Inc.",
          "Bohemia Interactive",
          "Ubisoft Montreal",
          "Sports Interactive",
          "Chucklefish",
          "Brace Yourself Games",
          "Ubisoft Quebec",
          "Virtual Programming (Linux)",
          "Tarsier Studios",
          "Rockstar Toronto",
          "Expansive Worlds",
          "Rogue Planet Games",
          "Iron Gate AB",
          "TREBUCHET",
          "Blue Byte",
          "Berserk Games",
          "Rare Ltd",
          "Hardsuit Labs",
          "VALOFE",
          "Gamepires",
          "Fistful of Frags Team",
          "Playdead",
          "Fatshark",
          "Evil Mojo Games",
          "Innersloth",
          "Respawn Entertainment",
          "QLOC",
          "2K Czech",
          "BlueTwelve Studio",
          "ConchShip Games",
          "The Behemoth",
          "Avalanche Studios",
          "2K Marin",
          "Dimensional Ink Games",
          "Aspyr (Mac)",
          "Red Barrels",
          "Nicalis",
          "Landfall West",
          "BANDAI NAMCO Studios Inc.",
          "Grey Havens",
          "Turtle Rock Studios",
          "Edmund McMillen",
          "Smilegate RPG",
          "Stainless Games Ltd.",
          "Toys for Bob",
          "Wube Software LTD.",
          "Splash Damage",
          "Behaviour Interactive Inc.",
          "United Front Games",
          "Infinity Ward",
          "Free Reign Entertainment",
          "Mega Crit Games",
          "OVERKILL Software",
          "PlatinumGames",
          "Coffee Stain Studios",
          "Double Eleven",
          "Noio",
          "MY.GAMES",
          "Sandbox Interactive GmbH",
          "Playsaurus",
          "Paradox Tinto",
          "Primal",
          "Redbeet Interactive",
          "KAGAMI WORKS",
          "Forgotten Empires",
          "Torn Banner Studios",
          "Nimble Neuron",
          "Saber Interactive",
          "Noble Empire Corp.",
          "Team Cherry",
          "Ndemic Creations",
          "343 Industries",
          "Toronto",
          "Treyarch",
          "NS STUDIO",
          "Digital Extremes",
          "FromSoftware Inc.",
          "Licorice",
          "11 bit studios",
          "Konami Digital Entertainment",
          "Creobit",
          "Kunos Simulazioni",
          "Gunfire Games",
          "Trion Worlds",
          "Hyper Hippo Games",
          "Dennaton Games",
          "Galactic Cafe",
          "Lucas Pope",
          "U.S. Army",
          "System Era Softworks",
          "Red Hook Studios",
          "Endnight Games Ltd",
          "Avalanche Software",
          "Arkane Studios",
          "Colossal Order Ltd.",
          "Novalink",
          "Cryptic Studios",
          "Efecto Studios",
          "Kiev",
          "Warhorse Studios",
          "Irrational Games",
          "Firaxis Games",
          "KRAFTON",
          "Florian Himsl",
          "Ubisoft Montpellier",
          "Frozenbyte",
          "Instinct Games",
          "Beenox",
          "Rocksteady Studios",
          "Avalanche Studios",
          "Nixxes",
          "ZeniMax Online Studios",
          "Aurora Studio",
          "IO Interactive A/S",
          "Blue Mammoth Games",
          "Crate Entertainment",
          "KOG",
          "Inc.",
          "SCS Software",
          "Ghost Town Games Ltd.",
          "TaleWorlds Entertainment",
          "Tripwire Interactive",
          "Bloober Team SA",
          "No Brakes Games",
          "DoubleDutch Games",
          "Beat Games",
          "4A Games",
          "Massive Entertainment",
          "Deep Silver Volition",
          "Muse Games",
          "Digital Extremes",
          "Pandemic Studios",
          "Axolot Games",
          "Facepunch Studios",
          "Feral Interactive (Mac)",
          "Clifftop Games",
          "EA Canada & EA Romania",
          "Arrowhead Game Studios",
          "Smartly Dressed Games",
          "id Software",
          "Kitka Games",
          "Forgotten Empires",
          "Sledgehammer Games",
          "Rockstar North",
          "JOYCITY",
          "Standing Stone Games",
          "Keen Software House",
          "Victor Solodilov",
          "Shiro Games",
          "Denis Novikov",
          "Crowbar Collective",
          "Titan Forge Games",
          "Ruffian Games",
          "Colibri Games",
          "Supergiant Games",
          "Feral Interactive (Mac/Linux)",
          "Daybreak Game Company",
          "Creaky Corpse Ltd",
          "KAGAMI ├óÔÇª┬í WORKs",
          "Unknown Worlds Entertainment",
          "Red Storm",
          "vanripper",
          "Clever Endeavour Games",
          "Eidos-Montr├â┬®al",
          "Tantalus Media",
          "WB Games Montreal",
          "Team Psykskallar",
          "Obsidian Entertainment",
          "Rebuilt Games",
          "2K Boston",
          "Maxis",
          "New World Interactive",
          "Gearbox Software",
          "Double Fine Productions",
          "Flying Wild Hog",
          "and Ubisoft Shanghai",
          "MOBITECH LLC",
          "Codemasters",
          "Moon Studios GmbH",
          "OVERKILL - a Starbreeze Studio.",
          "CREATIVE ASSEMBLY",
          "VRChat Inc.",
          "Heroic Leap Games",
          "Wargaming Group Limited",
          "Gaijin Entertainment",
          "Hoobalugalar_X",
          "Relic Entertainment",
          "Crystal Dynamics",
          "PopCap Games",
          "RobTop Games",
          "Rebellion",
          "TLM Partners",
          "Edmund McMillen",
          "Io-Interactive A/S",
          "Youthcat Studio",
          "Bethesda Game Studios",
          "World Makers",
          "Feral Interactive",
          "Hazelight",
          "Squad",
          "Frictional Games",
          "No More Room in Hell Team",
          "Bennett Foddy",
        ]}
        title="Studio"
      />
    </div>
  );
};

export default options;
